# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /#top
    weight: 10
  - name: Anfahrt
    url: /#anfahrt
    weight: 20
  - name: Zeitplan
    url: /#zeitplan
    weight: 30
  - name: Ranglisten
    weight: 40
    url: /#ranglisten
