# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: red

# SEO
marketing:
  seo:
    site_type: Competition
    local_business_type: ""
    org_name: "BKTV"
    description: "Competition website for SaltOpen 2024 by BKTV in Mägenwil"
  analytics:
    google_analytics: "G-TS5ERQ8EY4"
    baidu_tongji: ""
    plausible: ""
    fathom: ""
    pirsch: ""
  verification:
    google: ""
    baidu: ""

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    align: "center"
    fixed_to_top: true
    show_search: false
    show_theme_chooser: true

# Site footer
footer:
  copyright:
    notice: ""

# Localization
locale:
  date_format: "02 Jan 2006"
  time_format: "15:04"
  offset: "+01"
