name = "Saltopen.ch"
license = "MIT"
licenselink = "https://github.com/mathewmeconry/saltopen-ch/blob/main/LICENSE.md"
description = "Wettkampf Webseite für Saltopen vom BKTV"

homepage = "https://github.com/mathewmeconry/saltopen-ch"

# If the theme has a single author
[author]
  name = "Mathias Scherer"
  homepage = "https://blockbite.ch/"
